{% set version = "2.0.3" %}

package:
  name: django-recaptcha
  version: {{ version }}

source:
  url: https://github.com/praekelt/django-recaptcha/archive/{{ version }}.tar.gz
  sha256: fef5f23cce795e9c6d3b1d5812637416e244137f04ea04bb0d3975b21af8354a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import captcha"

about:
  home: http://github.com/praekelt/django-recaptcha
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Django recaptcha form field/widget app.'

extra:
  recipe-maintainers:
    - ocefpaf
