{% set version = "1.4.0" %}

package:
  name: django-recaptcha
  version: {{ version }}

source:
  url: https://github.com/praekelt/django-recaptcha/archive/{{ version }}.tar.gz
  sha256: c93aedc3a22ae6bfa6d923d3dfb1226f679eca5cf6eb3e055196574e4c657041

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - captcha

about:
  home: http://github.com/praekelt/django-recaptcha
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Django recaptcha form field/widget app.'

extra:
  recipe-maintainers:
    - ocefpaf
