{% set version = "2.0.2" %}

package:
  name: django-recaptcha
  version: {{ version }}

source:
  url: https://github.com/praekelt/django-recaptcha/archive/{{ version }}.tar.gz
  sha256: b40d3c49033985e7b68fd8dceb7661aa41eed8d2e7f3134f2f21b6f69b0e7f2c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import captcha"

about:
  home: http://github.com/praekelt/django-recaptcha
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Django recaptcha form field/widget app.'

extra:
  recipe-maintainers:
    - ocefpaf
