{% set version = "1.5.0" %}

package:
  name: django-recaptcha
  version: {{ version }}

source:
  url: https://github.com/praekelt/django-recaptcha/archive/{{ version }}.tar.gz
  sha256: 0c72b5fbb566c41b68b204fe5ecd688cfd79e72fa5994062e424822e60c530f2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - captcha

about:
  home: http://github.com/praekelt/django-recaptcha
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Django recaptcha form field/widget app.'

extra:
  recipe-maintainers:
    - ocefpaf
