travis:
  secure:
    BINSTAR_TOKEN: fJ9cCUNgmTfjP1Y5lvtGFaqIVdL2KVDIgWTteT53XViREZTLeafzTn9egbKeq5VhTNOaDzycROiOOBhnMMmwC9sPi9m+5AMAhq+L6paDktkKv7FU6qf1qvHL5eA32rftpv7vYR5dhJ1WaSmrf1mOieRPZJDDzv0OHRuYa3b9NqPaJJwd3AyszQun5DuCtLvIyuE0C4B71hyRm6EmFct8sHh6c9ajZcyoMswnVXiCtHIzBuXR0IeZLougO1nauXiWpcz7W1huyiPz9Qt2MjxW+WE+sBsj2ADGtoxpC0gGgqKl4nkbRl7mmSBtL8AWV/QH5z8eTWrvfCJAsMSjt0wsqgF3qeRIiUTtQclmeic52PzibfclHt9919AygjR6cX0tjYyD4V77znRXlv9gl1YQKH9t/Hpnif7qpR4sgMUMNb4NWntArzXKHN5n4tUy02gScosuXExRSAp53LstW/xBRSlzZsdl7UlbizTSgHBVgMDza+BFJ4MBlu56PMPRlXTDj9Ju4RzlJYCSoGapyHDsWl68pM9ztk1tXTB74Fi8DUhUE8ON3vijukpADYsVQ/NYyhorPTsAtmD1deZzqi3sVFtNh16SwqbMsFTiNsMfDFK+7E5DRwnnyZ1GaJVYCmlHHrWX5macjvxgMnFzuUobbXp+h0F8/BR7CkkfUTTXHt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
