travis:
  secure:
    BINSTAR_TOKEN: WvuILLWAg7B0Lfl3SyXeZF5IRC4USKEUCbTuBMWk9cS4gDOOXKR5t/MlvxPtEUEHErcHuax+zKsi6a3PrFVTozHVrIPZBR3oXz6i6wY13FYO15zsYiSYye2U5nKf0DqpWXhlHMWEDudThBDmsehI0FqDF65HMgy0a0jhJ+1fl8h6ZYnJIYIs6WJaAUUPOC3X5s2ZVI5YZhKHBKoNjupzXuw2VpQSoPIFK/nCcyzj0IhblMCDGYCti1VPs4uKV1zWzUM+LuhKkhZ8faPE+HYIq7AcMUqhHK44msMLzN9deLN0vMyQzGmaXiL5C42bwbfiz/lTnnBeLsso3fuFd7ZJLyAbp5TimtuYrvd8sXXwJv48VaKOVUeuh+/P98G29hBKPYFDgVKO6q856l5+vwoOEYcbwwogi0vN/7Ub7r1HhMtWJcI1/A6bPhO8oABCzMXtKOSk1RbdVRPJq//MBgOBUzlLKQHtyxV615n8/m0hjk8fRMD98PzpSI8yQlx8klCHEReVJVSR8HK2VIw2+On8EC1JpxYnWPU5N1omGt74Oli6iFOp6AsXZZhFuDiEO6571dV7EJjUVbRlXNrwcKH32ZiuCFdsHfNCi2mzc10QtfnDSGpc4TkT/4GVYKYv6BQTI3+BSnH7ei1eN5nuptC+N5sJBYjhbBReZyVip06lLys=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
