travis:
  secure:
    BINSTAR_TOKEN: Ng9DMr+kDNQxvsUcjbJ9VAUg5al5VNquGEdpiAqO7lJGmyIvOB39ehMIdQ+niotSR97OgoZQ1PEi1X0Jti0KIdaPMFY8LIpj/7MQ/UWxGZxLV9QGAmS1K3k2zEYovHsD6bOBcT+7YhLvw2EQ0SCkRNS4Nu3Cd96nsExvqgnu9TH0s8G9uh2FMrYnG3nIwB+oTd79IcdyIHxz5DZ4JyG1w2wXY/CWBPz87G9jo68F+0mMJiP5jIXyfHCuF5mjoTBVTXoKlhrmL6EjRqECq8uwPf1Ua9ws559CaRzbKx7oPF/XU2uL6JjKcw8o+2lqMNkABHBm2DtmTuCdEroUU00oLb2+IckbyEx96NPHBiTQ9DZyJ3fD6KV4XB2dr569gCOngAzvkK4MvNr7OK3JlbMNTpgqOxjXbfHcC72nnhR0WTiAnJzFA67Vj7bNo1bJe1t33y2v+MhGa4XeLPgHULEIaMS7xqg/Tc4S4SF4q2vFoNOuaraLWQGJY2fFNlhlzW2BTZX8GsCt04Z/vTumPFynVGL3VXA8B3ma2ACe8tVgLjMXuNziP3WJlY/istYPxTHBSDK6UDZ3qJM6n51k+V2OIjBpSZTUoCqNo9E9H0T6qZgrNMxh/3RgpOYysy+6N/gY8mOoFYyHVEHXJxXNsL8bLa/2nmf2D9cjwQYZP19OmP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
