travis:
  secure:
    BINSTAR_TOKEN: B8KNgAsKxxgmscsbkQMy4meH6svY5tnEf6R6aPdtpqgfrPIBQMzNSZxkeWz9KZsqF0iq7P+Tu5jDFsIi9/M2D5riyHP9Wpv4FNrAsvYqZGVWWY2HkqAiQRxD7gGrldy5X2/iotil7g7xQ+kQZ3E/AlFS9Dmm+3PikFXgh3PvFvndBZzmmpBebRg0iMn7P/fiaCZQJtwhS70VeGXsJWpDL6t8XnmCYzup36ewGcz5xFYAknz5+Q9eE+tUBb7IrCcR3ipAilUKu9CkfMGKbPdz5NExbrhOkMt7n+D+q05iupi9gEcKqb8Y9hKoG+qq5gLHQ+HhaTcwbNJG7hWgKULY0AqUVQr343u/CkSHXofloCiauuJTN2nZIiy7py3U/MRcRir/NxDjoFWa2l89uIfvUCRkRrZmFnVHkbV9epZbLdC6g4i/djRM5ar5aA+9D2MAhnmA66LoEIxxMMRSC4TiSipR61YZqFxaKlkAckbwwjaYNrW6uT3tAd4ylw1/MQGO9iwZSv1mNDtPl5xoQhLjw6tcoFzcmkK9FE/fnJ6QfLNWRDL7VSs1h2WK0fPlXc78pyabQvoz4z1/6o0gwTQxyzMXrDNaH5Roh2WQw+S1hVjMYsvdEcrkSYEgfJwyVvooLuPexpld3kHJt9uQh1bQmevreHYKYhF128ZQ6NQkiPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
