travis:
  secure:
    BINSTAR_TOKEN: pdNWQYsAu0fgOwH+okmqelNASKP5yFwnP5tVJjeokL+4YKPL3V6SWWZdjIL+vAlhtL0b/Eqtbi6pzNuesfHk8Lq/Hxi5n5zb716H6Yjzg6KnCUBe07T3p3k4OZ5aIwvS7rcv6ZqNJGFtlBrIDZE2slQd0NkSWKjlXgYxB3hpYtbySZvWzPf+HL31OH5jDlZlUNgbztBNA4qiVg1qqfh7/x2EYvSebL/sbW4EigqE8349mQjhkbPoAVSExZaqfTpK1KWtrbyvxrXDUUzbw7cXvzFndwvKlU4l+yWp/Q4Mp6zSibomAj+8gmHzqA2bjLkaSl2bTcjKy6tBVwZ2mDzbnEikoC0dglDcpqT5PkiEImm0pYR92vxE2SJnM2oC9ixL2AHIHumo7hwNBZ1zGfWyX41Ty6gCAPL65u1MwCpdDVjdF8W6GMJ3eo6A2PhEATu8sGfk9mfDrks2EzqV9ilOQoOLZLiyENAdVmAXCkkQL6OLqNcLegJC3hpuWo9B6hZfcXdgNB7YDgI2tFU2/vY+AXEQPwdm79HSVOVx/8SUYl+prNI2Xk4xPC7YguRGQE+elSXu1gAVryqmlvLQjhqJoDRq1A+qFBPidhg0K6vGfFNEJRIZxhAfejz/oYoIsKgSG+nkTyzL6Ozc3tPWP1lMP01nfSSxKtUqp5yahOPUiBA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
